version: '3.8'
services:
  bot:
    image: 'node:14'
    env_file: .env
    volumes:
    - ./:/usr/src/app
    working_dir: /usr/src/app
    command: [ "npm", "run", "dev" ]
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor

volumes:
  mongo:



