version: '3.8'
services:
  bot:
    image: 'node:14'
    env_file: .env
    volumes:
    - ./:/usr/src/app
    working_dir: /usr/src/app
    command: [ "npm", "run", "dev" ]
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo:



