version: '3.8'
services:
  bot:
    image: 'node:14'
    env_file: .env
    volumes:
    - ./:/usr/src/app
    working_dir: /usr/src/app
    command: [ "npm", "run", "start" ]
    depends_on:
      - redis

  redis:
    restart: always
    image: 'bitnami/redis:latest'
    volumes:
      - redis-helper-tgtoadbot:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  redis-helper-tgtoadbot:


