name: helper_tgtoadbot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 dotenv: ^3.0.0
 gato: ^0.0.3+3
 get_it: ^7.1.3
 mongo_dart: ^0.5.0+1
 rxdart: ^0.27.1
 slugify: ^2.0.0
 teledart: ^0.1.6


dev_dependencies:
  pedantic: ^1.10.0
  build_runner:
